apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    imageregistry: "https://hub.docker.com/"
    version: "project/demo/v1"
    Billing: "demo/service/8500$"
    platform: cloud/aws
    statging: env/QA
spec:
  containers:
  - name: nginx-perl-container
    image: nginx:perl
    ports:
    - containerPort: 80