apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
spec:
  containers:
  - name: nginx-perl-container
    image: nginx:perl
    ports:
    - containerPort: 80
data:
  username: admin
  access_level: "1"