apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx-perl-container
    image: nginx:perl
    ports:
    - containerPort: 80
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 81
    