apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-example-configmap
spec:
  containers:
  - name: nginx-perl-container
    image: nginx:perl
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
         name: myconfigmap