apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80


---

apiVersion: v2
kind: Pod
metadata:
  name: nginx-pod-2
spec:
  containers:
  - name: nginx-perl-container
    image: nginx:perl
    ports:
    - containerPort: 80

