apiVersion: v1
kind: Service

metadata:
  name: nginx-clusterip

spec:
 selector:
    app: nginx
 ports:
    - port: 8080
      targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-cluster
spec:
  containers:
  - name: nginx-perl-cluster
    image: nginx:perl
    ports:
    - containerPort: 80